- name: Creates directory
  file:
    path: ~/web
    state: directory


# - name: Extract project files
#   unarchive:
#     src: "artifact.tar.gz"
#     dest: "~/web"


- name: Copying required file archive
  template:
    src: "backend.tar.gz"
    dest: "~/web"

- name: Extract files
  shell: |
    cd ~/web
    tar -xzvf backend.tar.gz 

- name: Start app
  shell: |
    cd ~/web
    npm install
    pm2 stop default
    pm2 start npm -- start


