- name: Creates directory
  file:
    path: ~/web/udapeople-backend
    state: directory


# - name: Extract project files
#   unarchive:
#     src: "artifact.tar.gz"
#     dest: "~/web/udapeople-backend"

- name: Copying required file archive
    shell: |
      cd ~/web/udapeople-backend
      aws s3 cp s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}/artifact.tar.gz .

- name: Extract files and start app
  shell: |
    cd ~/web/udapeople-backend
    tar -xzvf artifact.tar.gz 
    npm install
    pm2 stop default
    pm2 start npm -- start

# - name: Start app
#   shell: |
#     cd ~/web/udapeople-backend
#     npm install
#     pm2 stop default
#     pm2 start npm -- start


