- name: Creates directory
  file:
    path: ~/web/udapeople-backend
    state: directory


# - name: Extract project files
#   unarchive:
#     src: "artifact.tar.gz"
#     dest: "~/web/udapeople-backend"

- name: Copying required file archive
  shell: |
    cd ~/web/udapeople-backend
    aws s3 cp s3://udapeople-11640059212/backend.tar.gz .
    aws s3 rm --recursive s3://udapeople-11640059212
- name: Extract files and start app
  shell: |
    cd ~/web/udapeople-backend
    tar -xzvf backend.tar.gz 
    npm install
    pm2 stop default
    pm2 start npm -- start

# - name: Start app
#   shell: |
#     cd ~/web/udapeople-backend
#     npm install
#     pm2 stop default
#     pm2 start npm -- start


